const teams = [
  {
    id: 0,
    name: "MI",
    icon: "https://www.pngall.com/wp-content/uploads/2017/04/Mumbai-Indians-Logo-PNG.png",
    totalPlayers: 15,
    topBatsman: "Rohit Sharma",
    topBowler: "Arshad Khan",
    championshipCount: 5,
    Fullname: "Mumbai Indians",
    players: [
      {
        id: "10",
        name: "Rohit Sharma",
        role: "Batsman",
        country: "India",
        img: "https://www.mumbaiindians.com/static-assets/images/players/large/3852.png?v=3.77&w=200",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "11",
        name: "Dewald Brevis",
        role: "Batsman",
        country: "Foriegn",
        img: "https://www.mumbaiindians.com/static-assets/images/players/large/84562.png?v=3.77&w=200",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "12",
        name: "Nehal Wadhera",
        role: "Batsman",
        country: "India",
        img: "https://www.mumbaiindians.com/static-assets/images/players/large/69657.png?v=3.77&w=200",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "13",
        name: "Arshad khan",
        role: "Bowler",
        country: "India",
        img: "https://www.mumbaiindians.com/static-assets/images/players/large/82839.png?v=3.77&w=200",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "14",
        name: "Arjun Tendulkar",
        role: "Bowler",
        country: "India",
        img: "https://www.mumbaiindians.com/static-assets/images/players/large/69659.png?v=3.77&w=200",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "5",
        name: "Hrithik Shokeen",
        role: "Bowler",
        country: "India",
        img: "https://www.mumbaiindians.com/static-assets/images/players/large/71155.png?v=3.77&w=200",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
    ],
  },
  {
    id: 1,
    name: "RCB",
    icon: "https://i.pinimg.com/originals/e7/aa/43/e7aa43ca345d7813b1f5607d182baf91.png",
    totalPlayers: 10,
    topBatsman: "Virat Kohli",
    topBowler: "Harshal Patel",
    championshipCount: 0,
    Fullname: "Royal Challengers Bangalore",
    players: [
      {
        id: "0",
        name: "Virat Kohli",
        role: "Batsman",
        country: "India",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/2.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "1",
        name: "Faf du Plessis",
        role: "Batsman",
        country: "Foreigen",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/94.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "2",
        name: "Finn Allen",
        role: "Batsman",
        country: "Forigen",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/595.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "3",
        name: "Anuj Rawat",
        role: "Bowler",
        country: "India",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/534.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "4",
        name: "Dinesh Karthik",
        role: "Batsman",
        country: "India",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/13.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "5",
        name: "Glenn Maxwell",
        role: "All-rounder",
        country: "Forigen",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/28.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "6",
        name: "Michael Bracewell",
        role: "All-Rounder",
        country: "Forigen",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1465.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "7",
        name: "Harshal Patel",
        role: "Bowler",
        country: "India",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/114.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "8",
        name: "Shahbaz Ahamad",
        role: "Bowler",
        country: "India",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/523.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
      {
        id: "9",
        name: "Akash Deep",
        role: "Bowler",
        country: "India",
        img: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1007.png",
        price: "2.50Cr",
        isPlaying: "Yes",
      },
    ],
  },
  {
    id: 2,
    name: "KKR",
    icon: "https://cricketbettingexpert.net/wp-content/uploads/2023/03/1-Kolkata-Knight-Riders-768x768.webp",
    totalPlayers: 15,
    topBatsman: "Rohit Sharma",
    topBowler: "Jasprit Bumrah",
    championshipCount: 5,
    Fullname: "Kolkata-Knight-Riders",
    players: [
      { id: "0", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "1", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "2", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "3", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "4", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "5", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "6", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "7", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
    ],
  },
  {
    id: 3,
    name: "RR",
    icon: "https://www.pngall.com/wp-content/uploads/2017/04/Rajasthan-Royals-Logo-PNG.png",
    totalPlayers: 15,
    topBatsman: "Rohit Sharma",
    topBowler: "Jasprit Bumrah",
    championshipCount: 5,
    Fullname: "Rajasthan Royals",
    players: [
      { id: "0", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "1", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "2", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "3", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "4", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "5", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "6", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "7", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "8", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
    ],
  },
  {
    id: 4,
    name: "CSK",
    icon: "https://www.pngall.com/wp-content/uploads/2017/04/Chennai-Super-Kings-Logo-PNG.png",
    totalPlayers: 15,
    topBatsman: "Rohit Sharma",
    topBowler: "Jasprit Bumrah",
    championshipCount: 5,
    Fullname: "Chennai Super Kings",
    players: [
      { id: "0", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "1", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "2", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "3", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "4", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "5", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "6", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "7", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
    ],
  },
  {
    id: 5,
    name: "DC",
    icon: "https://www.pngall.com/wp-content/uploads/2017/04/Deccan-Chargers-Logo-PNG.png",
    totalPlayers: 15,
    topBatsman: "Rohit Sharma",
    topBowler: "Jasprit Bumrah",
    championshipCount: 5,
    Fullname: "Deccan Chargers",
    players: [
      { id: "0", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "1", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "2", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "3", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "4", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "5", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
    ],
  },
  {
    id: 6,
    name: "PKBS",
    icon: "https://www.pngall.com/wp-content/uploads/2017/04/Kings-XI-Punjab-Logo-PNG.png",
    totalPlayers: 15,
    topBatsman: "Rohit Sharma",
    topBowler: "Jasprit Bumrah",
    championshipCount: 5,
    Fullname: "Kings-XI-Punjab",
    players: [
      { id: "0", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "1", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "2", name: "Rohit Sharma", role: "Batsman", country: "India" },
      { id: "3", name: "Jasprit Bumrah", role: "Bowler", country: "India" },
      { id: "4", name: "Rohit Sharma", role: "Batsman", country: "India" },
    ],
  },
  {
    id: 7,
    name: "SRH",
    icon: "../Home page/sunraisers.png",
    totalPlayers: 15,
    topBatsman: "Rohit Sharma",
    topBowler: "Jasprit Bumrah",
    championshipCount: 5,
    Fullname: "SunRaisers",
    players: [
      {
        id: "0",
        name: "Abhishek Sharma",
        role: "Batsman",
        country: "India",
        img: "https://www.sunrisershyderabad.in/uploads/image/SRH-6426a49e354b94.45488373nmt05aiw.png",
        price: "6.50 Cr",
        isPlaying: "Yes",
      },
      {
        id: "1",
        name: "Rahul Tripathi",
        role: "Batsman",
        country: "India",
        img: "https://www.sunrisershyderabad.in/uploads/image/SRH-6426ac88055703.29874138nei(qu$3.png",
      },
      {
        id: "2",
        name: "Aiden Markram",
        role: "Batsman",
        country: "India",
        img: "https://www.sunrisershyderabad.in/uploads/image/SRH-642fcec3ab4935.86088829un14m2ho.png",
      },
      {
        id: "3",
        name: "Bhuvneshwar Kumar",
        role: "Bowler",
        country: "India",
        img: "https://www.sunrisershyderabad.in/uploads/image/SRH-6426972db8bb36.78277625h34yrjpw.png",
      },
      {
        id: "4",
        name: "Heinrich Klaasen",
        role: "Keeper",
        country: "India",
        img: "https://www.sunrisershyderabad.in/uploads/image/SRH-642fcf029eafa4.730747431c7x4if6.png",
      },
      {
        id: "5",
        name: "Fazalhaq Farooqi",
        role: "Bowler",
        country: "India",
        img: "https://www.sunrisershyderabad.in/uploads/image/SRH-642eab91af9a13.13745534gb5)l$ks.png",
      },
    ],
  },
];
export default teams;
